# Site settings
title: "My Self-Directed MBA Journey"
description: "Documenting my journey through a self-designed MBA curriculum built through courses and certificates, books, and practical insights."
author: "Saeid Babaei"
email: "saeid.babayi@live.com"
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://saeid-babaei.github.io" # the base hostname & protocol for your site
github_username: "saeid-babaei"

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap

# Theme settings
#theme: jekyll-theme-modernist # Choose from Jekyll’s themes on GitHub Pages
#plugins:
#- jekyll-remote-theme
#- jekyll-feed
#- jekyll-seo-tag
#- jekyll-sitemap

# SEO settings
title_separator: "-"
social:
  twitter: "yourtwitterhandle"
  linkedin: "Saeid Babaei"
  github: "saeid-babaei"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Saeid Babaei"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5 # Number of posts per page on home page
paginate_path: "/page:num/"

# Optional analytics and comments
google_analytics: "G-9J2K02T72Z" # Replace with your Google Analytics ID
#comments:
#  provider: "disqus"
#  disqus:
#    shortname: "your-disqus-shortname"

# Navigation settings (optional)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Books"
    url: "/books/"
  - title: "Courses"
    url: "/courses/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact"

